Logic implemented with Fragments API.
Myst3ryX/MoneyTrackerXE pull request #4
Opened 2017-06-28 23:15 UTC by Myst3ryX

Created TabLayout + ViewPager in MainActivity. Classes created: BalanceFragment.java, ItemsFragment.java and ItemsAdapter.java (from inner-class).

2017-06-29 22:34 UTC, shushper requested changes

2017-06-29 22:34 UTC, shushper commented on app/src/main/java/com/myst3ry/moneytrackerxe/MainActivity.java
> +        setContentView(R.layout.activity_main);
Делай отступы пожалуйста между строчек. Ну нереально читать.

2017-06-29 22:34 UTC, shushper commented on app/src/main/java/com/myst3ry/moneytrackerxe/MainActivity.java
> +        mainActBar.setTitle(getString(R.string.budget_accounting));
Вместо этого можно просто писать setTitle() И вообще заголовок activity можно задавать из манифеста.

2017-06-29 22:34 UTC, shushper commented on app/src/main/java/com/myst3ry/moneytrackerxe/MainActivity.java
> +            if (position == 0) args.putString(ItemsFragment.ARG_TYPE, Item.EXP_TYPE);
Вот тут хоршо, аккуратно сделал. Но такие вещи лучше проверять через switch. Попробуй, тебе понравится! )

2017-06-29 22:34 UTC, shushper commented on app/src/main/res/layout/activity_balance.xml
> +<?xml version="1.0" encoding="utf-8"?>
У тебя BalanceFragment, значит и разметка должна называться fragmen_balance.

2017-06-29 22:34 UTC, shushper commented on app/src/main/res/layout/activity_temp_add.xml
> +<?xml version="1.0" encoding="utf-8"?>
Ты решил назвать экран переходным состоянием?))) Не определился temp ли это или add ?))

2017-06-30 04:53 UTC, Myst3ryX commented on app/src/main/res/layout/activity_temp_add.xml
> +<?xml version="1.0" encoding="utf-8"?>
Это add, но пока temp))) И чтобы не забыть, что это в итоге temp - это add, сделана соответствующая приписка) Поправил))

2017-06-30 05:08 UTC, Myst3ryX commented on app/src/main/java/com/myst3ry/moneytrackerxe/MainActivity.java
> +            if (position == 0) args.putString(ItemsFragment.ARG_TYPE, Item.EXP_TYPE);
Я сначала сделал через switch. Посидел, посмотрел, подумал и удалил. Как мне показалось, для трех элементов конструкция выглядит громоздкой (7 строчек против 3), к тому же нет default-значения. Обычно делаю switch по-умолчанию от 4 элементов или от 3 с дефолтным. Так то я его и сам люблю)))

2017-06-30 06:04 UTC, Myst3ryX commented on app/src/main/java/com/myst3ry/moneytrackerxe/MainActivity.java
> +        mainActBar.setTitle(getString(R.string.budget_accounting));
Понял. Сделаю из манифеста.

2017-07-02 20:44 UTC, merged