Google Sign-In Auth is integrated
Myst3ryX/MoneyTrackerXE pull request #8
Opened 2017-07-08 22:02 UTC by Myst3ryX

Google Services Auth is integrated to the app. Logic is implemented with Google Sign-In Authorization. Created AuthActivity.java as main auth screen. Auth screen styled in activity_auth.xml. Generated new google-services.json file with project/client info. Created new Result files: AuthResult.java (result for Google Sign-In operation) and BalanceResult.java (result for checking balance operation). Added resources such as: icon.png (for launcher), logo.png, gplus_button.png and bg_intro.png (for auth screen).

2017-07-10 20:29 UTC, shushper requested changes

2017-07-10 20:29 UTC, shushper commented on app/src/main/java/com/myst3ry/moneytrackerxe/AuthActivity.java
> +                            startActivity(new Intent(AuthActivity.this, MainActivity.class));
Зачем тут делать startActivity? Ты же всё равно finish вызываешь и мы вернёмся к предыдущей активити

2017-07-10 20:29 UTC, shushper commented on app/src/main/res/layout/activity_auth.xml
> +        android:paddingBottom="@dimen/padding_auth_images"
Вот из-за таких вот paddingBottom у тебя вёрстка какая-то кривая получилась. Зачем это лишнее пространство. Если хочешь отсступ от других элементов юзай маргин.

2017-07-10 20:29 UTC, shushper commented on app/src/main/res/layout/activity_auth.xml
> +        android:paddingBottom="44dp"
тут тоже лушче маргин если нужне отступ

2017-07-10 20:29 UTC, shushper commented on app/src/main/res/layout/activity_auth.xml
> +        android:layout_height="265dp"
Вот вместо того чтобы делать задануую высоту, сделай wrap_content и поиграйся с android:scaleType. Также, если выбрать на превьюшке nexus4 у тебя картинка убегает с экрана. То есть вёрстка получилась не гибкой. Имхо, нужно верстать на RelativeLayout.

2017-07-10 21:05 UTC, Myst3ryX commented on app/src/main/java/com/myst3ry/moneytrackerxe/AuthActivity.java
> +                            startActivity(new Intent(AuthActivity.this, MainActivity.class));
При использовании тут только finish(), без startActivity(), эффекта перехода в MainActivity нет. Переход был только при повторном нажатии "авторизации". Добавление строки 'android:parentActivityName=".MainActivity"' в манифест, данную проблему не решает. Для тестирования я использовал 5.1.1 (API 22) на реальном устройстве.

2017-07-12 09:50 UTC, Myst3ryX commented on app/src/main/java/com/myst3ry/moneytrackerxe/AuthActivity.java
> +                            startActivity(new Intent(AuthActivity.this, MainActivity.class));
Убрал finish() как избыточный код. С ним переход на MainActivity работал некорректно. Оставил переход по startActivity().

2017-07-17 04:39 UTC, merged